/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.Persona.PersonaController;
import controlador.tda.lista.ListaEnlazadaServices;
import controlador.utiles.TipoOrdenacion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Persona;
import vista.ModeloTablas.TablaPersonas;

/**
 *
 * @author Gigabyte
 */
public class Frm_Ordenamiento extends javax.swing.JDialog {

    private TablaPersonas tp = new TablaPersonas();
    private PersonaController pc = new PersonaController();
    private final Integer cantidad = 10000;

    /**
     * Creates new form Frm_Ordenamiento
     */
    public Frm_Ordenamiento(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        cargarTabla();
    }

    public void cargarTabla() {
        tp.setLista(pc.getListaPersona());
        tblPersona.setModel(tp);
        tblPersona.updateUI();
        pc.setPersona(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxMetodoOrdenacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxOrdenOrdenamiento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxAtributo = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        btnCrearLista = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersona = new javax.swing.JTable();
        labelTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manipulación de Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel1.setText("Método de Ordenación:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(11, 28, 126, 26);

        cbxMetodoOrdenacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shell", "QuickSort" }));
        jPanel3.add(cbxMetodoOrdenacion);
        cbxMetodoOrdenacion.setBounds(155, 28, 133, 26);

        jLabel2.setText("Orden de Ordenamiento:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(11, 79, 132, 16);

        cbxOrdenOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));
        jPanel3.add(cbxOrdenOrdenamiento);
        cbxOrdenOrdenamiento.setBounds(155, 76, 133, 22);

        jLabel3.setText("Ordenar por:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(318, 28, 75, 26);

        cbxAtributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "apellido", "telefono", "cedula" }));
        jPanel3.add(cbxAtributo);
        cbxAtributo.setBounds(405, 28, 130, 26);

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnFiltrar);
        btnFiltrar.setBounds(420, 80, 99, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(8, 66, 554, 136);

        btnCrearLista.setText("Crear Lista");
        btnCrearLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearLista);
        btnCrearLista.setBounds(8, 19, 95, 29);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setLayout(null);

        tblPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPersona);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 530, 240);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 210, 550, 280);
        jPanel1.add(labelTime);
        labelTime.setBounds(20, 510, 530, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 560);

        setSize(new java.awt.Dimension(591, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearListaActionPerformed
        // TODO add your handling code here:
        generarLista();
    }//GEN-LAST:event_btnCrearListaActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        if (cbxMetodoOrdenacion.getSelectedIndex() == 0) {

            try {
                ordenarShell();
            } catch (Exception ex) {
                Logger.getLogger(Frm_Ordenamiento.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                ordenarQuickSort();
            } catch (Exception e) {
                 Logger.getLogger(Frm_Ordenamiento.class.getName()).log(Level.SEVERE, null, e);

            }
        }

    }//GEN-LAST:event_btnFiltrarActionPerformed
    public void generarLista() {

        for (int i = 0; i < cantidad; i++) {

            pc.getPersona().setNombre(pc.generarNombresAleatorios());
            pc.getPersona().setApellido(pc.generarApellidosAleatorios());
            pc.getPersona().setEmail((pc.getPersona().getNombre() + pc.getPersona().getApellido() + "@hotmail.com"));
            pc.getPersona().setTelefono(pc.generarNumeros());
            pc.getPersona().setCedula(pc.generarNumeros());
            if (pc.guardar()) {

//                JOptionPane.showMessageDialog(null, "Lista Creada con Exito", "OK", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo crear la Lista", "Error", JOptionPane.ERROR_MESSAGE);
            }
            cargarTabla();
        }

    }

    public void ordenarQuickSort() throws Exception {
        ListaEnlazadaServices<Persona> listaP = pc.getListaPersona();
        long inicio = System.currentTimeMillis();
        System.out.println("ordenando");
        System.out.println(listaP.getLista().getSize() - 1);
        listaP.getLista().ordenar_QuickSort(String.valueOf(cbxAtributo.getSelectedItem()), listaP.getLista().toArray(), 0, listaP.getLista().getSize() - 1, orden(cbxOrdenOrdenamiento.getSelectedIndex()));
        long fin = System.currentTimeMillis();
        double tiempo = (double) ((fin - inicio) / 1000);
        labelTime.setText("Tiempo de Ordenacion QuickSort: " + tiempo + " seg");
        tp.setLista(listaP);
        tblPersona.setModel(tp);
        tblPersona.updateUI();
    }

    public void ordenarShell() throws Exception {
        ListaEnlazadaServices<Persona> listaP = pc.getListaPersona();
        long inicio = System.currentTimeMillis();
        listaP.getLista().ordenar_Shell(String.valueOf(cbxAtributo.getSelectedItem()), orden(cbxOrdenOrdenamiento.getSelectedIndex()));
        long fin = System.currentTimeMillis();
        double tiempo = (double) ((fin - inicio) / 1000);
        labelTime.setText("Tiempo de Ordenacion Shell: " + tiempo + " seg");
        tp.setLista(listaP);
        tblPersona.setModel(tp);
        tblPersona.updateUI();
    }

    public TipoOrdenacion orden(Integer or) {

        TipoOrdenacion ord = null;
        if (or == 0) {
            ord = TipoOrdenacion.DESCENDENTE;
        } else {
            ord = TipoOrdenacion.ASCENDENTE;
        }
        return ord;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Ordenamiento dialog = new Frm_Ordenamiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearLista;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbxAtributo;
    private javax.swing.JComboBox<String> cbxMetodoOrdenacion;
    private javax.swing.JComboBox<String> cbxOrdenOrdenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTime;
    private javax.swing.JTable tblPersona;
    // End of variables declaration//GEN-END:variables
}
